# Generated by Django 4.1.7 on 2023-02-23 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=25, null=True, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=12, unique=True, verbose_name='Documento')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Telefono')),
                ('sexo', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=2, null=True, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('S', 'SOLTERO(A)'), ('C', 'CASADO(A)'), ('D', 'DIVORCIADO(A)'), ('CO', 'CONVIVIENTE')], max_length=2, null=True, verbose_name='Estado Civil')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('foto', models.ImageField(null=True, upload_to='fotoempleados/', verbose_name='Foto')),
                ('direccion', models.CharField(max_length=50, null=True, verbose_name='Direccion')),
                ('ingles', models.BooleanField(default=False, null=True, verbose_name='Ingles')),
                ('area', models.CharField(choices=[('EMP', 'EMPLEADO'), ('ADM', 'ADMINISTRADOR'), ('MNT', 'MANTENIMIENTO')], max_length=5, null=True, verbose_name='Area')),
                ('codigo_contable', models.CharField(max_length=25, null=True, verbose_name='Codigo Contable')),
                ('inicio_contrato', models.DateField(null=True, verbose_name='Inicio de Contrato')),
                ('fin_contrato', models.DateField(null=True, verbose_name='Fin de Contrato')),
                ('cargo', models.CharField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('CONTROLER', 'CONTROLER'), ('VIGILANCIA', 'VIGILANCIA')], max_length=20, null=True, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Salario')),
                ('jornal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Jornal')),
                ('bono', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True, verbose_name='Bono')),
                ('movilidad', models.BooleanField(default=False, null=True, verbose_name='Movilidad')),
                ('carne_essalud', models.CharField(max_length=50, null=True, verbose_name='Carne ESSLAUD')),
                ('carne_cupss', models.CharField(max_length=50, null=True, verbose_name='Carne CUPPS')),
                ('cuenta_haberes', models.CharField(max_length=15, null=True, verbose_name='Cuenta Haberes')),
                ('asignacion_familiar', models.BooleanField(default=False, null=True, verbose_name='Asignacion Familiar')),
                ('hora_entrada', models.TimeField(null=True, verbose_name='Hora de Entrada')),
                ('pension', models.CharField(choices=[('ONP', 'ONP'), ('AFP HABITAT', 'AFP HABITAT'), ('AFP INTEGRA', 'AFP INTEGRA'), ('AFP PRIMA', 'AFP PRIMA'), ('AFP PROFUTURO', 'AFP PROFUTURO')], max_length=20, null=True, verbose_name='Pension')),
                ('educacion', models.CharField(choices=[('PRIMARIA', 'PRIMARIA'), ('SECUNDARIA', 'SECUNDARIA'), ('TECNICO', 'TECNICO'), ('UNIVERSITARIO', 'UNIVERSITARIO'), ('MAESTRIA', 'MAESTRIA'), ('TITULADO', 'TITULADO')], max_length=20, null=True, verbose_name='Educacion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=255, verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=150, verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime(2023, 2, 23, 6, 8, 37, 46543), verbose_name='Fecha de ingreso')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visitas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=12, verbose_name='Documento')),
                ('turno', models.CharField(choices=[('DIA', 'DIA'), ('TARDE', 'TARDE'), ('NOCHE', 'NOCHE')], max_length=15, verbose_name='Turno')),
                ('orden_servicio', models.CharField(max_length=150, verbose_name='Orden de Servicio')),
                ('orden_produccion', models.CharField(max_length=150, verbose_name='Orden de Produccion')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_salida', models.TimeField(null=True, verbose_name='Hora de Salida')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('kilos', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Kilo')),
                ('firma', models.ImageField(upload_to='firmas/', verbose_name='Firma')),
                ('validacion', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frankweb.area', verbose_name='Area')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frankweb.cliente', verbose_name='Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frankweb.producto', verbose_name='Producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frankweb.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Produccion',
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12, verbose_name='Documento')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('hora_entrada', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora Entrda')),
                ('hora_salida', models.TimeField(default=django.utils.timezone.now, verbose_name='Fecha Salida')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('estado', models.IntegerField(default=0, verbose_name='Estado')),
                ('observacion', models.CharField(default='Ninguna', max_length=250, verbose_name='Obervacion')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frankweb.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'ordering': ['id'],
            },
        ),
    ]
