# Generated by Django 4.1.7 on 2023-02-23 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 6, 9, 32, 649144), verbose_name='Fecha de ingreso'),
        ),
    ]
