# Generated by Django 4.1.7 on 2023-02-23 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankweb', '0003_alter_visitas_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 6, 10, 55, 745524), verbose_name='Fecha de ingreso'),
        ),
    ]
