# Generated by Django 4.1.7 on 2023-02-23 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankweb', '0004_alter_visitas_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 6, 16, 30, 601824), verbose_name='Fecha de ingreso'),
        ),
    ]
