# Generated by Django 4.1.7 on 2023-02-23 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankweb', '0005_alter_empleados_direccion_alter_visitas_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='visitas',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 6, 21, 19, 736665), verbose_name='Fecha de ingreso'),
        ),
    ]
