# Generated by Django 4.1.7 on 2023-02-23 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankweb', '0006_remove_empleados_cargo_alter_visitas_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='fecha_hora',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 6, 35, 47, 661565), verbose_name='Fecha de ingreso'),
        ),
    ]
